### ISSUE TITLE
Steps where not resolved in all cases

### ISSUE THREAD

**Issue by MS-Astra** [cucumber/vscode#143] opened 2023-01-30 13:24 UTC
### 👓 What did you see?

![image](https://user-images.githubusercontent.com/6927280/215486015-61c4dc2e-dcf5-42b4-a445-4cb85aeecae2.png)

### ✅ What did you expect to see?

All steps should be detected.

### 📦 Which tool/library version are you using?

Windows10
vscode 1.74.3
Cucumber ext. v1.7.0

### 🔬 How could we reproduce it?

1. Clone https://github.com/tbeede/python-cucumber.git
2. Install Cucumber 1.7.0
3. Open file features/create_folder.feature
4. The following line should not be resolved as expacted.
https://github.com/tbeede/python-cucumber/blob/master/features/create_folder.feature#L7

### 📚 Any additional context?
settings.json

```
{
    "cucumber.glue": [

        "src/test/**/*.java",
        "features/**/*.js",
        "features/**/*.jsx",
        "features/**/*.ts",
        "features/**/*.tsx",
        "features/**/*.php",
        "features/**/*.py",
        "tests/**/*.py",
        "tests/**/*.rs",
        "features/**/*.rs",
        "features/**/*.rb",
        "*specs*/**/.cs"
    ],
    "cucumber.features": [
        

        "src/test/**/*.feature",
        "features/**/*.feature",
        "tests/**/*.feature",
        "*specs*/**/.feature"
    ],
}
```

**Comment by nicopaez** [comment] 2023-03-07 21:27
Same here but running on MacOS 12.5.1, VSCode 1.76.0

**Comment by kieran-ryan** [comment] 2023-10-08 17:22
Hi @MS-Astra, thanks for raising. The link shared appears to have become inactive, so currently unable to reproduce as mentioned. Are you able to provide a copy of the repository you used or indicate whether you found a resolution? Likewise @nicopaez?

Note: If you are using the `@step` decorator with Behave, this is not supported and you will need to migrate to `@given`, `@when`, and `@then`.

If the issue can no longer be reproduced or if we do not have an understanding of the environment in which the issue was raised, I would make the recommendation that we close the issue and reopen it if becomes necessary.

**Comment by kieran-ryan** [comment] 2023-12-29 22:47
@MS-Astra, @nicopaez; located a [fork of the linked python-cucumber repository](https://github.com/alibugra/python-cucumber/tree/master).

The undetected step definition pattern in this case was:

```python
@when('user adds a folder with name "{folder_name}"')
def step_impl(context, folder_name):
    context.settings_page.create_folder(folder_name)
```

### Issue

The [Cucumber Language Service](https://github.com/cucumber/language-service) - which implements language support for the extension - interprets named arguments (such as `{folder_name}`) as [Cucumber Expression custom parameter types](https://github.com/cucumber/cucumber-expressions#custom-parameter-types) - which need to be defined outside the step definition pattern. You will observe this error from the Output window (see below image).

```console
[Info  - 21:20:03] Scheduling reindexing in 3000 ms
[Info  - 21:20:06] Reindexing file:///Users/<user>/projects/python/python-cucumber
[Info  - 21:20:07] * Found 7 feature file(s) in ["src/test/**/*.feature","features/**/*.feature","tests/**/*.feature","*specs*/**/.feature"]
[Info  - 21:20:07] * Found 24 steps in those feature files
[Info  - 21:20:07] * Found 10 glue file(s) in ["src/test/**/*.java","features/**/*.js","features/**/*.jsx","features/**/*.ts","features/**/*.tsx","features/**/*.php","features/**/*.py","tests/**/*.py","tests/**/*.rs","features/**/*.rs","features/**/*.rb","*specs*/**/.cs"]
[Info  - 21:20:07] * Found 0 parameter types in those glue files
[Info  - 21:20:07] * Found 7 step definitions in those glue files
[Error - 21:20:07] * Step Definition errors: Error: This Cucumber Expression has a problem at column 31:

user adds a folder with name "{folder_name}"
                              ^-----------^
Undefined parameter type 'folder_name'.
Please register a ParameterType for 'folder_name'
    ...
    at u (/Users/<user>/.vscode/extensions/cucumberopen.cucumber-official-1.7.0/out/extension.js:454:11308)
```

![](https://raw.githubusercontent.com/cucumber/vscode/main/images/vscode-output.png)

The Language Service does not provide support for the default step matcher used by behave (which uses the Python [parse](https://pypi.org/project/parse/) package). However, where patterns in that format overlap with the syntax of Cucumber Expressions, matches are detected.

The extension README documenting 'Behave' support is perhaps slightly misleading in this regard, lacking this detail; and likewise the 'python-cucumber' repository does not actually use Cucumber step patterns - though of course uses gherkin which the Cucumber team defines.

### Mitigating the issue

#### Use anonymous/positional arguments instead of named arguments

Cucumber Expressions and Behave's default matcher both support 'anonymous' parameters. Thus, simply removing the name from the parameters will treat values passed to the step definition as positional arguments rather than keyword arguments; and will be detected by the Cucumber extension AND executable by Behave - matching anything passed to it.

```python
@when('user adds a folder with name "{}"')
def step_impl(context, folder_name):
    context.settings_page.create_folder(folder_name)
```

I have created a [fork of python-cucumber that uses unnamed parameters](https://github.com/kieran-ryan/python-cucumber/tree/unnamed-parameters).

#### Use regex matcher

Behave's regex matcher can be used alternatively, and regex is supported by the extension. Though this is perhaps a developer-unfriendly alternative (see [Behave documentation on Regular Expressions](https://behave.readthedocs.io/en/stable/regular_expressions.html)).

#### Migrate to using Cucumber Expressions with Behave

Use [Behave Cucumber Matcher](https://github.com/kieran-ryan/behave-cucumber-matcher) to enable support for Cucumber Expressions in Behave. Follow the [README](https://github.com/kieran-ryan/behave-cucumber-matcher#behave-cucumber-matcher) to see how to integrate it.

```console
pip install behave-cucumber-matcher
```

Once you've integrated Cucumber Expressions support, you will have a number of different options in how you want to use those expressions. It is best to consult the [Cucumber Expressions documentation](https://github.com/cucumber/cucumber-expressions) in this regard. However, some considerations are outlined below.

Ideally Behave would provide this support natively. There is an [open issue on Cucumber Expressions support natively in Behave](https://github.com/behave/behave/issues/968), which would be an ideal scenario - I would encourage you both to upvote it.

##### Create custom Cucumber Expressions types

Creating the below Cucumber Expressions parameter type would require no change to the original step definition pattern. The `regexp` keyword argument defines the patterns to match.

```python
color_parameter = ParameterType(
    name="folder_name",
    regexp="<add your regex for matching a valid folder name here>",
    type=str,
    transformer=lambda s: s,
    use_for_snippets=True,
    prefer_for_regexp_match=False,
)
```

##### Use native Cucumber Expressions types

With the below example, we replace the quotations and the original named parameter with the Cucumber Expressions `string` type. This will match gherkin text in quotations.

```python
@when('user adds a folder with name {string}')
def step_impl(context, folder_name):
    context.settings_page.create_folder(folder_name)
```

##### Use Regex within the pattern

Cucumber Expressions support regex, which can be used alternatively to parameter types or native Cucumber Expressions types. You can use regex in part or all of the expression.

##### Migrate from generic @step decorator

Behave's generic `@step` decorator is unsupported in Cucumber by design as it has been considered that patterns should rarely fall into all three contexts (Given/When/Then). You can still execute it, but it won't be detected by the extension. However, decorating the same step definition with each required decorator works.

```python
@given('user adds a folder with name "{}"')
@when('user adds a folder with name "{}"')
@then('user adds a folder with name "{}"')
def step_impl(context, folder_name):
    context.settings_page.create_folder(folder_name)
```

### Resolution

For me, this issue can be marked resolved by updating the documentation to clarify and simplify some of the above comments. I will raise a PR time-allowing.

I will leave it out up to you both whether you want to open a feature request on the Cucumber Language Service for the default Behave matcher; though we currently only support Cucumber Expressions and Regular Expressions across our language support.

**Comment by MS-Astra** [comment] 2024-01-02 15:16
@kieran-ryan Thank you for the detailed clarification of the reported behaviour. For my own projects I will try to use anonymous arguments instead of named arguments.

Great Work!

**Closed** 2024-01-02 15:16 UTC
Labels: :book: documentation
