### ISSUE TITLE
Extension 'Cucumber' is configured as a formatter but it cannot format 'Gherkin'-files

### ISSUE THREAD

**Issue by jjorgenson-aya** [cucumber/vscode#185] opened 2023-11-20 23:17 UTC
### 👓 What did you see?

When attempting to format my feature files, I get this error message
![DefaultFormatter](https://github.com/cucumber/vscode/assets/134334573/4cca8d5b-7348-4fdd-a6e6-ffe1f5cec7bc)

### ✅ What did you expect to see?

I expected to see the file format correctly, or a prompt to set the default formatter with this Cucumber extension as an option.

### 📦 Which tool/library version are you using?

- Cucumber extension CucumberOpen.cucumber-official 1.7.0
- Node v18.18.2

### 🔬 How could we reproduce it?

1. Ensure there are no formatters set for .feature files
2. Right click on a .feature file
3. Click on 'Format Document'
4. The error will appear.

### 📚 Any additional context?
In my user settings, I have:
```json
  "[feature]": {
    "editor.defaultFormatter": "CucumberOpen.cucumber-official"
  }
```
I have this extension installed as well: [alexkrechik.cucumberautocomplete](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete), but I don't see formatting settings turned on pointing to them.

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment] 2023-11-21 22:59
@jjorgenson-aya, was unable to reproduce as of yet. Could you provide a screenshot of the output of the Cucumber Language Server when this happens from the 'Output' window in the panel next to the terminal? Not sure on root cause here, but can occur for a number reasons (e.g. with [ESLint](https://stackoverflow.com/questions/69748283/extension-eslint-is-configured-as-formatter-but-it-cannot-format-javascript)).

To eliminate some possibilities, does the issue still occur with the following conditions met:

- The [cucumberautocomplete](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete) extension is disabled? Including any configuration.
- The associated configuration is removed from settings at both the user and workspace levels?

**Comment by jjorgenson-aya** [comment] 2023-11-24 22:32
@kieran-ryan thank you for your response!
This error seems to occur when I have both extensions enabled, but removed the cucumberautocomplete from the settings.json as the formatter. When I have the cucumberautocomplete disabled, and reinstall Cucumber, I don't get a prompt to format the document at all. When I do the hotkey, I get this error. I see the cucumber extension listed when searching the marketplace for `category:formatters feature`, but it's already installed.
![NoFormatter](https://github.com/cucumber/vscode/assets/134334573/da6ff689-c69a-4d4c-a134-92ac9a1a1ce2)
Nothing occurs in the output tab when I trigger this error.

**Comment by kieran-ryan** [comment] 2023-12-23 23:24
Have been unable to reproduce @jjorgenson-aya unfortunately. Would it be possible to construct a [Minimal Reproducible Example](https://www.google.ie/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjlj5r_0qaDAxUlkFwKHUd_DXAQFnoECBEQAw&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMinimal_reproducible_example%23%3A~%3Atext%3DIn%2520computing%252C%2520a%2520minimal%2520reproducible%2Cto%2520be%2520demonstrated%2520and%2520reproduced.&usg=AOvVaw399odp-jUSwdDkWG0KIqN6&opi=89978449) (MRE) that demonstrates the issue - perhaps a small repo? A video even might be helpful - showing extensions window, local & user settings, etc. Interested to understand if any fix required or whether there's a conflict with the Autocomplete extension that we should document.

The errors I have triggered are as follows - using macOS, which may be a point of difference:

1. With 'cucumberautocomplete' and 'cucumber' not installed, and formatter set to 'cucumber'; I get the error:

    ```console
    Configure Default Formatter
    Extension 'CucumberOpen.cucumber-official' is configured as formatter but not available. Select a different default formatter to continue.
    ```
2. With file extension set to `.Gherkin` and 'cucumber' configured as formatter for 'Gherkin'; or with neither extension installed, I get the error:

    ```console
    There is no formatter for 'plaintext' files installed.
    ```

> This error seems to occur when I have both extensions enabled, but removed the cucumberautocomplete from the settings.json as the formatter. When I have the cucumberautocomplete disabled, and reinstall Cucumber, I don't get a prompt to format the document at all. When I do the hotkey, I get this error. I see the cucumber extension listed when searching the marketplace for `category:formatters feature`, but it's already installed.

1. With this experiment, were you applying settings at user level AND within the workspace? Or just one of them? Perhaps removing settings for both plugins at User level may help?
2. What version of Visual Studio Code are you using?
3. What file extension are you giving the feature files? `.feature`?

If we cannot reproduce or narrow down the root cause, we may have to close the issue - so the more detail the better. Thanks again for raising

**Comment by kieran-ryan** [comment] 2024-03-27 22:14
@jjorgenson-aya, closing for now as unable to reproduce and discern whether relates to this extension or the other mentioned extension; and without the local environment and user settings. Will keep an eye out for this and if any further information you can provide, we will reopen the issue and try to resolve the issue. Thanks again for your interest in the project 👍

**Closed by kieran-ryan** 2024-03-27 22:14 UTC
Labels: :thinking: cannot reproduce, :baby_bottle: incomplete
