### ISSUE TITLE
No support glue js file?

### ISSUE THREAD

**Issue by longb1997** [cucumber/vscode#92] opened 2022-08-10 08:45 UTC
Hi, it works like a charm if I use ts file, but js just have not found

[Info  - 3:44:10 PM] * Found 0 glue file(s) in ["features/**/*.php","features/**/*.rb","e2e/step_definitions/*.ts","e2e/step_definitions/*.js","features/**/*.py","src/test/**/*.java","*specs*/**/.cs"]

**Comment by aslakhellesoy** [comment] 2022-08-13 06:03
This is a dupe of https://github.com/cucumber/language-service/issues/42

**Closed by aslakhellesoy** 2022-08-13 06:03 UTC
