### ISSUE TITLE
VS Code extension cannot contact Cucumber Language Server

### ISSUE THREAD

**Issue by alanstronach** [cucumber/vscode#179] opened 2023-05-11 08:55 UTC
Since yesterday my Cucumber extension in VS Code has stopped working, 

[Error - 9:40:58 AM] Server initialization failed.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
[Error - 9:40:58 AM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603

**Comment by kieran-ryan** [comment] 2023-09-25 21:45
Thanks all for your contributions in flagging this issue. Marking this issue as a duplicate of #164. Please continue discussion on that ticket, which you can use to track the status. Thanks again ✌️

**Closed** 2023-09-25 21:47 UTC
