### ISSUE TITLE
Syntax highlighting and autocomplete not working with WSL

### ISSUE THREAD

**Issue by EZaykov** [cucumber/vscode#121] opened 2022-11-10 02:04 UTC
### 👓 What did you see?

![image](https://user-images.githubusercontent.com/42176041/200983017-2c0957fe-4415-4480-acf6-ad3c4dd705eb.png)

### ✅ What did you expect to see?

Syntax highlighting and autocomplete

### 📦 Which tool/library version are you using?

extension: v1.5.1
cucumber: v8.7.0

### 🔬 How could we reproduce it?

1. Install versions above
2. Create a any .feature file in  ```<root>/features``` folder
3. Look

 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by aslakhellesoy** [comment] 2022-11-11 23:25
Hmmm. Have you removed all other Cucumber/Gherkin extensions that might be interferring?

**Comment by EZaykov** [comment] 2022-11-12 07:07
> Hmmm. Have you removed all other Cucumber/Gherkin extensions that might be interferring?

yeah. Installed just ur extension

**Comment by nrawe** [comment] 2022-11-17 16:19
I can confirm the same behaviour when running this inside of a dev container, too.

**Comment by aslakhellesoy** [comment] 2022-11-18 13:04
I need an [mre](https://stackoverflow.com/help/minimal-reproducible-example) in a GitHub repo to reproduce this and provide a fix. Please create one and share the link to the repo.

**Comment by aslakhellesoy** [comment] 2022-12-08 13:55
I'll close this issue as incomplete soon unless someone can provide an mre.

**Comment by AlbertoFdzM** [comment] 2023-12-23 12:26
[Here you have a repo](https://github.com/AlbertoFdzM/course-codely-typescript-ddd) with this issue. feature files are under `tests/**/*.feature` that match with the extension default configuration.

**Comment by kieran-ryan** [comment] 2023-12-23 14:45
Thank you for the example @AlbertoFdzM! Appears to be the same as #174; users found that resolving v1.8 of the extension resolved the issue - which is blocked for release by a publishing issue (#189).

Would you first be able to advise whether you are seeing any of the Output in the screenshot at the top of this Issue? Would like to understand whether is related or separate. Assume you are also using WSL2?

To attempt to resolve, would you be able to manually download the [v1.8 release](https://github.com/cucumber/vscode/releases/tag/release%2Fv1.8.0) (`.vsix`) and [install directly](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix); and advise whether that resolves your issue?

**Comment by barrymichaeldoyle** [comment] 2024-01-02 14:20
> Thank you for the example @AlbertoFdzM! Appears to be the same as #174; users found that resolving v1.8 of the extension resolved the issue - which is blocked for release by a publishing issue (#189).
> 
> Would you first be able to advise whether you are seeing any of the Output in the screenshot at the top of this Issue? Would like to understand whether is related or separate. Assume you are also using WSL2?
> 
> To attempt to resolve, would you be able to manually download the [v1.8 release](https://github.com/cucumber/vscode/releases/tag/release%2Fv1.8.0) (`.vsix`) and [install directly](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix); and advise whether that resolves?

This works, I can't wait for it to get properly released to the market place!

**Comment by kieran-ryan** [comment] 2024-01-02 20:18
Awesome - cheers @barrymichaeldoyle!

@EZaykov or @nrawe, can you attempt the same - to manually install v1.8 - and advise if this resolves the issue for you? Would like to understand whether we can close the ticket or otherwise capture a root cause to action a fix

**Comment by kieran-ryan** [comment] 2024-01-14 17:02
> > Thank you for the example @AlbertoFdzM! Appears to be the same as #174; users found that resolving v1.8 of the extension resolved the issue - which is blocked for release by a publishing issue (#189).
> > Would you first be able to advise whether you are seeing any of the Output in the screenshot at the top of this Issue? Would like to understand whether is related or separate. Assume you are also using WSL2?
> > To attempt to resolve, would you be able to manually download the [v1.8 release](https://github.com/cucumber/vscode/releases/tag/release%2Fv1.8.0) (`.vsix`) and [install directly](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix); and advise whether that resolves?
> 
> This works, I can't wait for it to get properly released to the market place!

Now available in the marketplace @barrymichaeldoyle 👍

**Comment by kieran-ryan** [comment] 2024-03-24 13:59
Marking closed through linked issue and based on feedback - with fix now available in the marketplace:

> This works, I can't wait for it to get properly released to the market place!

No further MRE provided beyond what was fixed. If issue remains in certain cases and an MRE can be provided, issue will be reopened. 👍

> I'll close this issue as incomplete soon unless someone can provide an mre.

**Closed by kieran-ryan** 2024-03-24 13:59 UTC
Labels: :bug: bug, :baby_bottle: incomplete
