### ISSUE TITLE
Generate step definition does not work

### ISSUE THREAD

**Issue by cvacalares** [cucumber/vscode#214] opened 2024-02-05 19:14 UTC
### 👓 What did you see?
After installing the plugin, the generate step definition doesn't work for me.
After pressing crtl + ., there's no option to generate the step definition (as was shown on the plugin's feature).
![image](https://github.com/cucumber/vscode/assets/15913865/cd560909-75da-4301-ac5f-4a47aede5a88)

### ✅ What did you expect to see?
After pressing crtl + ., an option to generate the step definition is presented.

### 📦 Which tool/library version are you using?
Visual Studio Code: 1.86.0.
Java: 17.0.6
Cucumber: 1.8.1

### 🔬 How could we reproduce it?

1. Install 'Visual Studio Code' version '1.86.0.'.
2. Install 'Cucumber' version '1.8.1.'.
3. Go to a feature file.
4. Enter "Then this is a new step definition."
5. Press ctrl + ..

![image](https://github.com/cucumber/vscode/assets/15913865/cb351976-4142-4e14-ad4b-bdd4654164a4)
### 📚 Any additional context?
All other feature of the plugin works.
I can navigate to the step definition.
Autocomplete works.
Only the generate step definition is not working for me.
We tried it on another computer. We still can't make the generate step definition work.

**Comment by kieran-ryan** [comment] 2024-02-05 23:15
Hi @cvacalares, thanks for raising! Would need a little more information to diagnose and reproduce the issue - specifically around glue files.

Preferably, if you can create and share a small repository demonstrating the issue as an MRE (Minimum Reproducible Example), that will make it easier to diagnose and resolve.

1. What language are your glue files (or step definitions) written in?
2. Relative to the workspace you are running the extension against, what path are they stored at e.g. 'features/steps/**/*.py'? Default expected paths are specified in the [extension manifest](https://github.com/cucumber/vscode/blob/977a69114e5338dfb98fc3fdbb61543ad52feafb/package.json#L58).
3. Have you configured any extension settings? If so, can you share those settings?

One point to note is the following [generate step definition README notice](https://github.com/cucumber/vscode?tab=readme-ov-file#generate-step-definition):

> _IMPORTANT:_ Generate step definition will only be enabled if there is at least one existing step definition. This is so that the extension can determine the programming language for the step definition, and provide choices for existing files to add it to.

**Comment by cvacalares** [comment] 2024-02-08 01:24
What language are your glue files (or step definitions) written in? - Java
Relative to the workspace you are running the extension against, what path are they stored at e.g. 'features/steps/**/*.py'? src/test/java/com/motorola/salesforce/java
Have you configured any extension settings? If so, can you share those settings?
Are there any errors within the [VSCode Output window](https://github.com/cucumber/vscode/blob/main/images/vscode-output.png) for the Cucumber Language Server?
![image](https://github.com/cucumber/vscode/assets/15913865/bd2dc581-8c16-4445-90f7-deb9719cf1b1)

**Comment by kieran-ryan** [comment] 2024-02-10 19:34
@cvacalares, taking another look at your original image, I believe the `Examples:` keyword is partially visible. Is this a Scenario Outline? Can you confirm whether temporarily removing the `Examples:` portion of the test marks the step as 'undefined' and enables the generate step definition action?

Unfortunately, marking steps as undefined in Scenario Outlines is currently unsupported (cucumber/language-service#149). A step must be marked 'undefined' (and will be underlined) to enable the generate step definition action.

**Comment by kieran-ryan** [comment] 2024-02-27 21:59
Closing issue as caused by lack of Scenario Outline support.

Feel free to reach out if any update @cvacalares, however commenting on the linked issue is preferable.

Thanks for raising!

**Closed as not planned by kieran-ryan** 2024-02-27 21:59 UTC
Labels: :no_good: wontfix
