### ISSUE TITLE
Inline `#` considered a comment with syntax highlighting

### ISSUE THREAD

**Issue by jimmyko** [cucumber/vscode#153] opened 2023-04-07 00:09 UTC
### 👓 What did you see?

When I use "#" (hash) in the step statement, it will highlight the following text as a comment

### ✅ What did you expect to see?

According to the [documentation](https://cucumber.io/docs/gherkin/reference/), `#` should not be considered as a comment when there is text before `#`

> Comments are only permitted at the start of a new line, anywhere in the feature file. They begin with zero or more spaces, followed by a hash sign (`#`) and some text.

### 📦 Which tool/library version are you using?

I am using CucumberOpen.cucumber-official v1.7.0

### 🔬 How could we reproduce it?

1. Install CucumberOpen.cucumber-official version 1.7.0
2. Open a feature file with any name 
3. Copy and paste the below content
```gherkin
Feature: This is the example of using hash character

  # this is a real coment
  Scenario: This is a scenario
    Given There is # after Given keyword
    When I enable CucumberOpen.cucumber-official 
    Then I should see text before and after # is in same syntax color
```
4. See the text after Given keyword has 2 different syntax text color before and after `#`

![image](https://user-images.githubusercontent.com/3071329/230514327-e6c80f8a-171c-41cd-86c4-2ca7384a5cab.png)

### 📚 Any additional context?

https://github.com/cucumber/vscode/blob/416c2f8862b32c8822db37549c5f76695b5ce159/syntaxes/gherkin-classic.tmLanguage#L104

Here is the change suggestion
```xml
<string>^\s*(#.*)</string>
```

**Comment by kieran-ryan** [comment] 2023-12-30 15:49
Thanks for raising @jimmyko, I was unable to reproduce locally and in the [Cucumber Monaco demo](https://cucumber.github.io/monaco/) - which uses the same [Cucumber Language Service](https://github.com/cucumber/language-service).

Would you be able advise whether you are still seeing the issue? If so, would it be possible to advise on the VSCode theme you are using? And whether you are using any extensions that may interfere with the syntax highlighting? Interested to know if was caused by an external factor, or otherwise how to reproduce.

**Comment by kieran-ryan** [comment] 2024-03-24 14:22
Closing as unable to reproduce and as the `.tmLanguage` is no longer part of the extension.

The original example also does not include underlining for any undefined steps - so curious whether a separate Cucumber extension is running in parallel or how is being run.

<img width="521" alt="cucumber-vscode-1 8 0" src="https://github.com/cucumber/vscode/assets/5904340/a995163f-082e-45f4-8c65-c16f18d1988a">

The `tmlLanguage` used by GitHub does match the highlighting shown however and is contained in an archived project ([cucumber-attic/cucumber-tmbundle](https://github.com/cucumber-attic/cucumber-tmbundle)).

Issue will be reopened if further information comes to light necessitating a fix or feature.

**Closed** 2024-03-24 14:22 UTC
Labels: :thinking: cannot reproduce, :baby_bottle: incomplete
