### ISSUE TITLE
Server Initialisation Failure

### ISSUE THREAD

**Issue by DasInternaut** [cucumber/vscode#159] opened 2023-05-05 09:06 UTC
Coincidental to a vscode update, I now see a server initialisation failure for this extension, on startup of vscode.  Symptoms are a Server Initialisation error, with the following output:

[Error - 10:00:58 AM] Server initialization failed.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_php_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603 
[Error - 10:00:58 AM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: abort(Assertion failed: bad export type for `tree_sitter_php_external_scanner_create`: undefined). Build with -s ASSERTIONS=1 for more info.
  Code: -32603

Additionally, colour coding of my Gherkin stops working until I uninstall the extension and re-start.

Reproducing? Your best chance of reproducing the issue locally, I think, would be:

- Windows 10
- Visual Studio Code as below:

Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by LukasLewandowski** [comment] 2023-05-05 09:09
I have the same issue, probably after recent update of VSC

**Comment by mojo2012** [comment] 2023-05-05 09:30
Same here, just updated an bamm ... :-( Right in the moment I wanted to write some tests ...

**Comment by nodeg** [comment] 2023-05-05 15:38
Duplicate of https://github.com/cucumber/vscode/issues/155.

**Comment by klaukl** [comment] 2023-05-10 02:36
Happens for me but on MacOS 13.3.1

**Comment by kieran-ryan** [comment] 2023-10-08 17:46
Thanks all for raising, closing as a duplicate of #155, please continue any discussion there, thanks!

**Closed by kieran-ryan** 2023-10-08 17:46 UTC
